resources:

- name: jenkins
  type: docker-image
  source:
    repository: jenkins/jenkins

- name: jenkins-logimethods
  type: docker-image
  source:
    repository: logimethods/jenkins
    username: ((docker-hub-username))
    password: ((docker-hub-password))

- name: github-repo-master
  type: git
  source:
    uri: https://((github-username)):((github-password))@github.com/((github-repo-location))/((github-repo-name)).git
    branch: master

jobs:

- name: push-to-github
  plan:
  - get: jenkins
    trigger: true
  - get: github-repo-master
  - task: push-github
    params:
      GITHUB_EMAIL: ((github-email))
      GITHUB_USERNAME: ((github-username))
      URL: ((api-url))
      DOCKER-HUB-REPO: ((docker-hub-repo))
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: helioncf/ubuntu1404-curl-git-jq-wget
      inputs:
      - name: github-repo-master
      outputs:
      - name: github-repo-modified
      run:
        path: github-repo-master/scripts/push-to-github
  - put: github-repo-master
    params: {repository: github-repo-modified}


- name: push-to-dockerhub
  plan:
  - get: jenkins-logimethods
  - get: github-repo-master
    passed: [push-to-github]
    trigger: true
  - put: jenkins-logimethods
    params: {build: ./github-repo-master, tag: ./github-repo-master/tag}
